### ISSUE TITLE
Fails on Firefox

### ISSUE THREAD

**Issue by omichelsen** [rt2zz/redux-persist-transform-compress#1]
This is not working for me on Firefox 47 on Mac, it can't read and decompress the strings again if using localStorage.

Using `compressFromUTF16 ` and `decompressFromUTF16` instead makes it work, but I have to fork your lib to do that. 

Maybe make it configurable, or switch completely to the UTF16 method? Don't know if there are any downsides to switching to UTF16.

**Comment by moimikey** [comment]
same issue here. latest chrome (53) on mac.

**Comment by rt2zz** [comment]
sounds like we should switch the default to compressFromUTF16

If you can please PR your fork and I will merge
